spring:
    datasource:
        url: {JDBC_DATABASE_URL}
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 1MB
            max-request-size: 3MB
    profiles:
        active: oauth-security

my-security:
    allowed-origin: "*"
    enable-https: true
