server:
  port: 8080
  error:
    include-stacktrace: on_param

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/skylibrary
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    date-format: yyyy-MM-dd

file:
  upload-dir: ./src/main/resources/static/images/covers

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG