spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/skylibrary
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    date-format: yyyy-MM-dd