server:
  port: 8080
  error:
    include-stacktrace: on_param

spring:
  profiles:
    active: "basic-security"
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2MB
      max-request-size: 5MB
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/skylibrary
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    date-format: yyyy-MM-dd

my-security:
  allowed-origin: http://localhost:5500
file:
  upload-dir: ./src/main/resources/static/images/covers

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
